### ISSUE TITLE
Error Network failed

### ISSUE THREAD

**Issue by Pengich** [cubicbyte/reddit-account-generator#18]
With Proxy 
HIDE_BROWSER = True

2023-11-27 00:39:57 ERROR Network failed with RecaptchaException.
2023-11-27 00:42:05 ERROR Network failed with IPCooldownException.

**Comment by cubicbyte** [comment]
> 2023-11-27 00:39:57 ERROR Network failed with RecaptchaException.

This is normal, this error means that too many captcha solves have been made from your IP. This is mainly because we solve captcha using voice recognition, and there is like a N/hour limit on this type of solution from one IP

> 2023-11-27 00:42:05 ERROR Network failed with IPCooldownException.

This means that from this IP was already registered an account recently (limit is 1 in 10 min)

So, the first error can't be solved, but the second one is more interesting. I have an idea, so I'll leave this issue until I solve it
