### ISSUE TITLE
[BUG] Captcha

### ISSUE THREAD

**Issue by Wikinger8** [cubicbyte/reddit-account-generator#7]
![image](https://github.com/cubicbyte/reddit-account-generator/assets/85295145/6542b19d-be03-40e4-8dbe-ac33af6f18ff)

It says that you need to solve another captcha but the programm just closed firefox and gave me an error.

It's in German, I hope that's not a problem.

**Comment by cubicbyte** [comment]
Strange, I've never seen the need to solve multiple captchas. In theory it's because the first attempt is unsuccessful, but it's unlikely.

**Comment by cubicbyte** [comment]
In any case, the selenium-recaptcha-solver library is responsible for solving the captcha. @thicccat688, what do you think about this error?

**Comment by thicccat688** [comment]
Hi, 

This is most likely happening due to the selenium-recaptcha-solver library not factoring in other languages for multiple audio challenges. 

The way we find out if 2 audio challanges are present is by using this XPATH:
`//div[normalize-space()="Multiple correct solutions required - please solve more."]`. 

Basically what this does is it looks for a div that has a text content of "Multiple correct solutions required - please solve more," so when the text is in German it doesn't identify that it needs to solve the audio challenge a second time. The fix I can incorporate for this would be locating the div without using its text content. 

Alternatively, if you're getting an error with the audio recognition it's because the ReCAPTCHA solver isn't set to solve German audio.

You can set it to solve german audio by passing the service_language parameter like this: 
`RecaptchaSolver(driver=test_driver, service_language='de-DE')`). 

You can set the solver to any language supported by the Google speech recognition API. You can find out if your language is supported here: https://cloud.google.com/speech-to-text/docs/speech-to-text-supported-languages

Feel free to make an issue or PR in the meantime and I'll implement a fix when I can.

Have a great day!

**Comment by cubicbyte** [comment]
Thanks for the detailed response. I decided to help you and created a PR with a solution to our problem and improved captcha error detection mechanism, so you can check it out when you can!

**Comment by Wikinger8** [comment]
> You can set it to solve german audio by passing the service_language parameter like this: `RecaptchaSolver(driver=test_driver, service_language='de-DE')`).

Where can I change this setting?

**Comment by cubicbyte** [comment]
> > You can set it to solve german audio by passing the service_language parameter like this: `RecaptchaSolver(driver=test_driver, service_language='de-DE')`).
> 
> Where can I change this setting?
> 

At the moment setting is not present in config file, so you need to change it manually in [this line](https://github.com/cubicbyte/reddit-account-generator/blob/5143f5b0420a42c6e2e8888d649b92de77e7b777/reddit_account_generator/maker.py#L123) of code.

By the way, in what language do you have captcha audio? Because regardless of the language (Ukrainian, Russian) my captcha audio is always in English

This info will help a lot

**Comment by Wikinger8** [comment]
The captcha audio is also in german.

**Comment by Wikinger8** [comment]
It said test_driver is not defined so I changed it to solver = RecaptchaSolver(driver, service_language='de-DE')

But now I get this error 
![image](https://github.com/cubicbyte/reddit-account-generator/assets/85295145/de2caa49-6266-401d-b8af-1cf38b4c7ce5)

Btw thanks for the quick help and really nice project.

**Comment by cubicbyte** [comment]
Well, you did everything right, but I have no idea what this error is related to. For some reason the captcha audio file is not being read. I'll try to solve it tomorrow

**Comment by Wikinger8** [comment]
Ok nice

**Comment by cubicbyte** [comment]
@Wikinger8 I fixed the problem in the simplest and most effective way possible - force set the language to English xD

Now you can use `git pull` (or just update app) and try
